version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/src/main/resources/scripts/testdata.sql:/docker-entrypoint-initdb.d/2-testdata.sql
    environment:
      POSTGRES_DB: kuehlfrank
      POSTGRES_USER: kuehlfrank
      POSTGRES_PASSWORD: VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "5432:5432"
  backend:
    image: docker.pkg.github.com/kuehlfrank/backend/backend:0.0.1
    container_name: kuehlfrank-backend
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
