version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/src/main/resources/scripts/testdata.sql:/docker-entrypoint-initdb.d/2-testdata.sql
    environment:
      POSTGRES_DB: kuehlfrank
      POSTGRES_USER: kuehlfrank
      POSTGRES_PASSWORD: VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: ghcr.io/kuehlfrank/backend:latest
    container_name: kuehlfrank-backend
    environment:
      - spring_profiles_active: 'dev'
      - spring_datasource_url: 'jdbc:postgresql://postgres:5432/kuehlfrank' # url / database
      - spring_datasource_username: 'kuehlfrank'
      - spring_datasource_password: 'VOUfsdHHdsZhGSS14PxurdT1u'
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
