version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/src/main/resources/scripts/testdata.sql:/docker-entrypoint-initdb.d/2-testdata.sql
    environment:
      POSTGRES_DB: kuehlfrank
      POSTGRES_USER: kuehlfrank
      POSTGRES_PASSWORD: VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: ghcr.io/kuehlfrank/backend:latest
    build:
      context: ./backend
    environment:
      - spring_profiles_active=dev
      - spring_datasource_url=jdbc:postgresql://postgres:5432/kuehlfrank # url / database
      - spring_datasource_username=kuehlfrank
      - spring_datasource_password=VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: ghcr.io/kuehlfrank/frontend:latest
    build:
      context: ./frontend
    # environment:
    # - REACT_APP_API_SERVER_URL=http://localhost:8081 # is hard coded into .env.docker
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
