version: "3"

services:
  database:
    container_name: database
    image: ghcr.io/kuehlfrank/database:latest
    build:
      context: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kuehlfrank
      POSTGRES_USER: kuehlfrank
      POSTGRES_PASSWORD: VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: ghcr.io/kuehlfrank/backend:latest
    build:
      context: ./backend
    environment:
      - spring_profiles_active=dev
      - spring_datasource_url=jdbc:postgresql://database:5432/kuehlfrank # url / database
      - spring_datasource_username=kuehlfrank
      - spring_datasource_password=VOUfsdHHdsZhGSS14PxurdT1u
    ports:
      - "8081:8080"
    depends_on:
      - database

  frontend:
    container_name: frontend
    image: ghcr.io/kuehlfrank/frontend:latest
    build:
      context: ./frontend
    # environment:
    # - REACT_APP_API_SERVER_URL=http://localhost:8081 # is hard coded into .env.docker
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
